[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#C231FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#210235"
font = "sans serif"

[browser]
gatherUsageStats = false
